sudo: required
services:
  - docker

before_install:
  - docker build -t omkarsurve4/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true omkarsurve4/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  regions: "ca-central-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-736622201017"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $"AWS_SECRET_KEY"